# =========================================
# APPLICATION
# =========================================
spring.application.name=fraud-detection-api

# =========================================
# SERVER CONFIG
# =========================================
server.port=8080

# =========================================
# LOGGING
# =========================================
logging.level.root=INFO
logging.level.com.example.fraud=DEBUG

# =========================================
# JACKSON JSON CONFIG
# =========================================
spring.jackson.serialization.indent-output=true

# =========================================
# FILE UPLOAD LIMITS (optional)
# =========================================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# =========================================
# PYTHON SCRIPT CONFIG
# =========================================
python.script.path=python/predict_risk.py
python.model.path=python/fraud_model.pkl

# =========================================
# ACTUATOR (optional but useful)
# =========================================
management.endpoints.web.exposure.include=health,info

# =========================================s
# DEVTOOLS (optional)
# =========================================
spring.devtools.restart.enabled=true