apiVersion: apps/v1
kind: Deployment

metadata:
  name: fraud-service
  namespace: payments

spec:
  replicas: 1

  selector:
    matchLabels:
      app: fraud-service

  template:
    metadata:
      labels:
        app: fraud-service

    spec:
      containers:
        - name: fraud-service
          image: 546068156511.dkr.ecr.us-east-1.amazonaws.com/fraud-service:v1
          imagePullPolicy: IfNotPresent

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: fraud-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: fraud-config
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: fraud-config
                  key: DB_NAME

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password

            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: fraud-config
                  key: KAFKA_BOOTSTRAP_SERVERS

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"